export const GLOBAL_CLEAR_STATE = 'GLOBAL_CLEAR_STATE';
export const AUTH_SET_SESSION = 'AUTH_SET_SESSION';
export const AUTH_CLEAR_SESSION = 'AUTH_CLEAR_SESSION';
export const WORKSPACE_REFRESH_LIST = 'WORKSPACE_REFRESH_LIST';
