export const AUTH_SET_SESSION = 'AUTH_SET_SESSION';
export const AUTH_SET_AUTHORIZED = 'AUTH_SET_AUTHORIZED';
export const WORKSPACE_SET_LIST = 'WORKSPACE_SET_LIST';
export const WORKSPACE_SET_CURRENT = 'WORKSPACE_SET_CURRENT';
export const WORKSPACE_SET_CURRENT_BY_INDEX = 'WORKSPACE_SET_CURRENT_BY_INDEX';
